#include <ultra64.h>
#include <macros.h>
#include "types.h"

extern void InitialPerspective();
extern void InitialScreenData();
extern void LoadMapData();
extern void SetSegment();
extern int LoadPressData();
extern void SearchList2();
extern void MakeCollision();
extern void func_80281780();
extern void func_802818BC();
extern void InitialGame();
extern void InitializeParams();
extern void func_8001C05C();
extern void func_80280FB0();
extern void func_802816B8();
extern void func_80093E60();
extern void *gLastMemoryPointer;

extern s16 gMapNumber;
extern u16 gBackgroundFlag;

extern s32 gScreenFlip;
extern s32 gRaceScreenMode;
extern s32 gScreenMode;
extern s32 gGameMode;
extern u16 gFogFlag;
extern u16 D_800DC5C8;
extern struct UnkStruct_800DC5EC *gScreen1;

extern s32 D_80287550;
extern s32 D_80287554;
extern f32 D_801647A4;
extern f32 D_80150130;

extern s32 gFreeMemoryPointer;
extern s32 gStaticMemoryPointer;

extern s32 D_8015F730;

extern f32 gWaterLevel;
extern s16 D_8015F6EA;
extern s16 D_8015F6EE;
extern s16 D_8015F6F2;
extern u16 D_8015F6E8;
extern u16 D_8015F6EC;
extern u16 D_8015F6F0;
extern s32 D_8015F59C;
extern s32 D_8015F5A0;
extern s32 D_8015F58C;
extern u16 D_8015F588;

extern s32 D_8015F580;

extern s32 D_00821D10;
extern s32 D_00825800;
extern s32 D_00831DC0;
extern s32 D_00835BA0;

extern s32 D_801625F8;
extern f32 D_801625FC;


// unk4 is buttonDown?
#ifdef MIPS_TO_C
//generated by mips_to_c commit 09d006c9da5d6bbcd31ac6ca5c9165c1a8533a83
void func_80281780(void) {
    if (gDebugFlag != 0) {
        if ((gCont1P->unk4 & 0xF0F) != 0) {
            if ((gCont1P->unk4 & 8) != 0) {
                D_800E86A8 = (u8)1;
            } else {
                if ((gCont1P->unk4 & 2) != 0) {
                    D_800E86A8 = (u8)2;
                } else {
                    if ((gCont1P->unk4 & 1) != 0) {
                        D_800E86A8 = (u8)3;
                    } else {
                        if ((gCont1P->unk4 & 4) != 0) {
                            D_800E86A8 = (u8)4;
                        } else {
                            if ((gCont1P->unk4 & 0x800) != 0) {
                                D_800E86A8 = (u8)5;
                            } else {
                                if ((gCont1P->unk4 & 0x200) != 0) {
                                    D_800E86A8 = (u8)6;
                                } else {
                                    if ((gCont1P->unk4 & 0x100) != 0) {
                                        D_800E86A8 = (u8)7;
                                    } else {
                                        *(void *)0x800F0000 = (u8)0;
                                    }
                                }
                            }
                        }
                    }
                }
            }
            bcopy(&D_80284ED0, &D_8018D9D0, 8);
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/code_80281780/func_80281780.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 09d006c9da5d6bbcd31ac6ca5c9165c1a8533a83
s32 func_80281880(s32 arg0) {
    s32 temp_v1;
    void *phi_v0;
    s32 phi_v1;
    s32 phi_v1_2;

    phi_v0 = &D_8018D9D0;
    phi_v1 = 0;
loop_1:
    phi_v1_2 = phi_v1;
    if (*phi_v0 != (arg0 + 0x800F0000)->unk-7958) {
        temp_v1 = phi_v1 + 1;
        phi_v0 = phi_v0 + 1;
        phi_v1 = temp_v1;
        phi_v1_2 = temp_v1;
        if (temp_v1 != 8) {
            goto loop_1;
        }
    }
    return phi_v1_2;
}
#else
GLOBAL_ASM("asm/non_matchings/code_80281780/func_80281880.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 09d006c9da5d6bbcd31ac6ca5c9165c1a8533a83
void func_802818BC(void) {
    s32 sp24;
    s32 sp1C;
    s32 temp_ret;
    s32 temp_ret_2;

    if (D_8018EDF3 != 2) {
        D_802874D8.unk1D = func_80281880(0);
        D_802874D8.unk1E = (s8) D_800E86A8;
        return;
    }
    temp_ret = func_80281880(0);
    sp1C = temp_ret;
    sp24 = temp_ret;
    temp_ret_2 = func_80281880(1);
    if (sp1C < temp_ret_2) {
        D_802874D8.unk1E = (s8) D_800E86A8;
        D_802874D8.unk1D = (s8) sp24;
        return;
    }
    D_802874D8.unk1E = (s8) D_800E86A9;
    D_802874F5 = (s8) temp_ret_2;
}
#else
GLOBAL_ASM("asm/non_matchings/code_80281780/func_802818BC.s")
#endif

#ifdef NON_MATCHING
void *InitialResultSequence(void) {
    s32 temp_t3;
    f32 temp_f;

    gMapNumber = 7;
    gBackgroundFlag = (u16)1;
    gScreenFlip = 0;
    D_80287550 = 0xFFFF;
    D_80287554 = 0;
    InitialPerspective();
    InitialScreenData();
    D_801647A4 = 60.0f;
    D_80150130 = 60.0f;
    gScreen1->unk2C = (u16)0x140;
    gScreen1->unk2E = (u16)0xF0;
    gScreen1->unk30 = (u16)0xA0;
    gScreen1->unk32 = (u16)0x78;
    gRaceScreenMode = 0;
    gFreeMemoryPointer = (s32) gStaticMemoryPointer;
    gScreenMode = 0;
    gGameMode = 0;
    LoadMapData(gMapNumber);
    D_8015F730 = (s32) gFreeMemoryPointer;
    SetSegment(0xB, LoadPressData(&D_00821D10, &D_00825800));
    SetSegment(6, LoadPressData(&D_00831DC0, &D_00835BA0));
    gWaterLevel = -2000.0f;
    D_8015F6EA = -0x15A1;
    D_8015F6EE = -0x15A1;
    D_8015F6F2 = -0x15A1;
    D_8015F6E8 = 0x15A1;
    D_8015F6EC = 0x15A1;
    D_8015F6F0 = 0x15A1;
    D_8015F59C = 0;
    D_8015F5A0 = 0;
    D_8015F58C = 0;
    D_8015F588 = (u16)0;
    gFogFlag = (u16)0;
    D_800DC5C8 = (u16)0;
    D_8015F580 = (s32) gFreeMemoryPointer;
    SearchList2(0x70067E8, -1);
    SearchList2(0x700AEF8, -1);
    SearchList2(0x700A970, 8);
    SearchList2(0x700AC30, 8);
    SearchList2(0x7000CE0, 0x10);
    SearchList2(0x7000E88, 0x10);
    SearchList2(0x700A618, -1);
    SearchList2(0x700A618, -1);
    SearchList2(0x70023F8, 1);
    SearchList2(0x7002478, 1);
    MakeCollision();
    func_80281780();
    func_802818BC();
    InitialGame();
    InitializeParams();
    func_8001C05C();
    func_80280FB0();
    func_802816B8();
    func_80093E60();
    D_801625F8 = (s32) gLastMemoryPointer - gFreeMemoryPointer;
    D_801625FC = ((f32) D_801625F8 / 1000.0f);
    return &D_801625F8;
}
#else
GLOBAL_ASM("asm/non_matchings/code_80281780/InitialResultSequence.s")
#endif
